apiVersion: v1
kind: Secret
metadata:
  name: registry-auth-secret
  namespace: mlops
  labels:
    app: registry-auth-secret
type: Opaque
data:
  htpasswd: YWRtaW46JDJ5JDA1JFF2aXduckF5SldaYXl2WXF3MDN6bnVobGFBMnpHNE5wQ3ROZ1Fib3lzZ3pkYWg1cXI3ZjND
