apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: mlops
  labels:
    app: postgres-service
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - name: tcp
    protocol: TCP
    port: 5432
    targetPort: 5432
